packages:
  - 'apps/*'
  - 'libs/*'
  - 'tools/*'

# Catalog for shared dependencies
catalog:
  '@nestjs/common': '^10.4.4'
  '@nestjs/core': '^10.4.4'
  '@nestjs/platform-express': '^10.4.4'
  '@nestjs/config': '^3.2.3'
  '@nestjs/swagger': '^7.4.2'
  '@nestjs/terminus': '^10.2.3'
  '@nestjs/cli': '^10.4.5'
  '@nestjs/schematics': '^10.1.4'
  '@nestjs/testing': '^10.4.4'
  'class-transformer': '^0.5.1'
  'class-validator': '^0.14.1'
  'helmet': '^7.1.0'
  'reflect-metadata': '^0.2.2'
  'rxjs': '^7.8.1'
  'winston': '^3.14.2'
  'nest-winston': '^1.10.0'
  '@swc/cli': '^0.4.0'
  '@swc/core': '^1.7.26'
  '@types/express': '^4.17.21'
  '@types/jest': '^29.5.12'
  '@types/node': '^22.5.4'
  '@types/supertest': '^6.0.2'
  '@typescript-eslint/eslint-plugin': '^8.5.0'
  '@typescript-eslint/parser': '^8.5.0'
  'eslint': '^9.10.0'
  'eslint-config-prettier': '^9.1.0'
  'eslint-plugin-prettier': '^5.2.1'
  'jest': '^29.7.0'
  'prettier': '^3.3.3'
  'source-map-support': '^0.5.21'
  'supertest': '^7.0.0'
  'ts-jest': '^29.2.5'
  'ts-loader': '^9.5.1'
  'ts-node': '^10.9.2'
  'tsconfig-paths': '^4.2.0'
  'typescript': '^5.6.2'
