apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
namespace: dev

replicas:
  - name: service-a
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - hpa-patch.yaml

images:
  - name: asia-southeast1-docker.pkg.dev/PROJECT_ID/app-registry/service-a
    newTag: dev-latest
