apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "service-a-backendconfig"}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: service-a
